In [1]:
pwd

'C:\\Users\\haha pc\\Documents'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('house_data.csv')

In [4]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
10,1736800520,20150403T000000,662500.0,3,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
11,9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
12,114101516,20140528T000000,310000.0,3,1.00,1430,19901,1.5,0,0,...,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
13,6054650070,20141007T000000,400000.0,3,1.75,1370,9680,1.0,0,0,...,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,1175000570,20150312T000000,530000.0,5,2.00,1810,4850,1.5,0,0,...,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
15,9297300055,20150124T000000,650000.0,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
16,1875500060,20140731T000000,395000.0,3,2.00,1890,14040,2.0,0,0,...,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
17,6865200140,20140529T000000,485000.0,4,1.00,1600,4300,1.5,0,0,...,7,1600,0,1916,0,98103,47.6648,-122.343,1610,4300
18,16000397,20141205T000000,189000.0,2,1.00,1200,9850,1.0,0,0,...,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
19,7983200060,20150424T000000,230000.0,3,1.00,1250,9774,1.0,0,0,...,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850
20,6300500875,20140514T000000,385000.0,4,1.75,1620,4980,1.0,0,0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
21,2524049179,20140826T000000,2000000.0,3,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
22,7137970340,20140703T000000,285000.0,5,2.50,2270,6300,2.0,0,0,...,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
23,8091400200,20140516T000000,252700.0,2,1.50,1070,9643,1.0,0,0,...,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
24,3814700200,20141120T000000,329000.0,3,2.25,2450,6500,2.0,0,0,...,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
25,1202000200,20141103T000000,233000.0,3,2.00,1710,4697,1.5,0,0,...,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
26,1794500383,20140626T000000,937000.0,3,1.75,2450,2691,2.0,0,0,...,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
27,3303700376,20141201T000000,667000.0,3,1.00,1400,1581,1.5,0,0,...,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
28,5101402488,20140624T000000,438000.0,3,1.75,1520,6380,1.0,0,0,...,7,790,730,1948,0,98115,47.6950,-122.304,1520,6235
29,1873100390,20150302T000000,719000.0,4,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21583,2025049203,20140610T000000,399950.0,2,1.00,710,1157,2.0,0,0,...,7,710,0,1943,0,98102,47.6413,-122.329,1370,1173
21584,952006823,20141202T000000,380000.0,3,2.50,1260,900,2.0,0,0,...,7,940,320,2007,0,98116,47.5621,-122.384,1310,1415
21585,3832050760,20140828T000000,270000.0,3,2.50,1870,5000,2.0,0,0,...,7,1870,0,2009,0,98042,47.3339,-122.055,2170,5399
21586,2767604724,20141015T000000,505000.0,2,2.50,1430,1201,3.0,0,0,...,8,1430,0,2009,0,98107,47.6707,-122.381,1430,1249
21587,6632300207,20150305T000000,385000.0,3,2.50,1520,1488,3.0,0,0,...,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
21588,2767600688,20141113T000000,414500.0,2,1.50,1210,1278,2.0,0,0,...,8,1020,190,2007,0,98117,47.6756,-122.375,1210,1118
21589,7570050450,20140910T000000,347500.0,3,2.50,2540,4760,2.0,0,0,...,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
21590,7430200100,20140514T000000,1222500.0,4,3.50,4910,9444,1.5,0,0,...,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21591,4140940150,20141002T000000,572000.0,4,2.75,2770,3852,2.0,0,0,...,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641
21592,1931300412,20150416T000000,475000.0,3,2.25,1190,1200,3.0,0,0,...,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
21593,8672200110,20150317T000000,1088000.0,5,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21594,5087900040,20141017T000000,350000.0,4,2.75,2500,5995,2.0,0,0,...,8,2500,0,2008,0,98042,47.3749,-122.107,2530,5988
21595,1972201967,20141031T000000,520000.0,2,2.25,1530,981,3.0,0,0,...,8,1480,50,2006,0,98103,47.6533,-122.346,1530,1282
21596,7502800100,20140813T000000,679950.0,5,2.75,3600,9437,2.0,0,0,...,9,3600,0,2014,0,98059,47.4822,-122.131,3550,9421
21597,191100405,20150421T000000,1575000.0,4,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21598,8956200760,20141013T000000,541800.0,4,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,7202300110,20140915T000000,810000.0,4,3.00,3990,7838,2.0,0,0,...,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21600,249000205,20141015T000000,1537000.0,5,3.75,4470,8088,2.0,0,0,...,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21601,5100403806,20150407T000000,467000.0,3,2.50,1425,1179,3.0,0,0,...,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
21602,844000965,20140626T000000,224000.0,3,1.75,1500,11968,1.0,0,0,...,6,1500,0,2014,0,98010,47.3095,-122.002,1320,11303
21603,7852140040,20140825T000000,507250.0,3,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,3448900210,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500.0,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [10]:
df.sort_values(by='price')

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1149,3421079032,20150217T000000,75000.0,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882
15293,40000362,20140506T000000,78000.0,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
465,8658300340,20140523T000000,80000.0,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
16198,3028200080,20150324T000000,81000.0,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
8274,3883800011,20141105T000000,82000.0,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
2141,1623049041,20140508T000000,82500.0,2,1.00,520,22334,1.0,0,0,...,5,520,0,1951,0,98168,47.4799,-122.296,1572,10570
18468,7999600180,20140529T000000,83000.0,2,1.00,900,8580,1.0,0,0,...,5,900,0,1918,0,98168,47.4727,-122.270,2060,6533
3767,1523049188,20150430T000000,84000.0,2,1.00,700,20130,1.0,0,0,...,6,700,0,1949,0,98168,47.4752,-122.271,1490,18630
16714,1322049150,20150305T000000,85000.0,2,1.00,910,9753,1.0,0,0,...,5,910,0,1947,0,98032,47.3897,-122.236,1160,7405
10253,2422049104,20140915T000000,85000.0,2,1.00,830,9000,1.0,0,0,...,6,830,0,1939,0,98032,47.3813,-122.243,1160,7680
13756,1788900230,20140722T000000,86500.0,3,1.00,840,9480,1.0,0,0,...,6,840,0,1960,0,98023,47.3277,-122.341,840,9420
5866,9320900420,20141014T000000,89000.0,3,1.00,900,4750,1.0,0,0,...,6,900,0,1969,0,98023,47.3026,-122.363,900,3404
3108,1721801591,20150219T000000,89950.0,1,1.00,570,4080,1.0,0,0,...,5,570,0,1942,0,98146,47.5098,-122.334,890,5100
16530,2114700500,20150418T000000,90000.0,1,1.00,560,4120,1.0,0,0,...,4,560,0,1947,0,98106,47.5335,-122.348,980,4120
7992,2734100835,20150303T000000,90000.0,1,1.00,780,4000,1.0,0,0,...,5,780,0,1905,0,98108,47.5424,-122.321,1150,4000
12551,1049010620,20140513T000000,90000.0,2,1.00,790,2640,1.0,0,0,...,7,790,0,1973,0,98034,47.7351,-122.178,1310,2064
18939,4239400300,20141129T000000,90000.0,3,1.00,980,2490,2.0,0,0,...,6,980,0,1969,0,98092,47.3170,-122.182,980,3154
17580,1423049019,20140523T000000,90000.0,2,1.00,580,7500,1.0,0,0,...,5,580,0,1943,0,98178,47.4852,-122.251,1700,11250
10770,795000765,20140616T000000,92000.0,2,1.00,760,5500,1.5,0,0,...,5,760,0,1947,0,98168,47.5045,-122.329,1040,5515
3321,2724200705,20141212T000000,95000.0,2,1.00,800,8550,1.0,0,0,...,7,800,0,1947,0,98198,47.4075,-122.294,1490,8550
14581,6929602721,20150408T000000,95000.0,2,1.00,960,7000,1.0,0,0,...,4,960,0,1918,0,98198,47.3864,-122.307,1850,8120
3805,7335400215,20150505T000000,95000.0,1,0.75,760,5746,1.0,0,0,...,5,760,0,1915,0,98002,47.3046,-122.215,970,6696
10585,6198400218,20140919T000000,95000.0,2,1.00,1070,20450,1.0,0,0,...,6,1070,0,1948,0,98058,47.4338,-122.183,1360,15581
5723,1788800630,20141029T000000,96500.0,3,1.00,840,12091,1.0,0,0,...,6,840,0,1959,0,98023,47.3281,-122.343,840,9324
5303,5128000010,20150105T000000,99000.0,2,1.00,960,8236,1.0,0,0,...,6,960,0,1948,0,98058,47.4698,-122.166,1260,8236
1218,3751600030,20140717T000000,100000.0,2,1.00,770,17334,1.0,0,0,...,7,770,0,1978,0,98001,47.2997,-122.269,1480,17334
16340,6146600170,20140703T000000,100000.0,2,0.75,660,5240,1.0,0,0,...,4,660,0,1912,0,98032,47.3881,-122.234,850,5080
5639,7224000980,20140610T000000,100000.0,4,1.00,1120,2685,1.0,0,0,...,5,860,260,1939,0,98055,47.4904,-122.203,1120,4838
15456,8856000545,20140507T000000,100000.0,2,1.00,910,22000,1.0,0,0,...,6,910,0,1956,0,98001,47.2777,-122.252,1326,9891
4563,1900000195,20140630T000000,100000.0,2,1.00,930,7623,1.0,0,0,...,6,930,0,1942,0,98166,47.4670,-122.349,1300,7641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14083,3625059043,20140904T000000,3300000.0,5,4.75,6200,13873,2.0,1,4,...,11,4440,1760,1989,0,98008,47.6050,-122.112,2940,13525
18199,3625059152,20141230T000000,3300000.0,3,3.25,4220,41300,1.0,1,4,...,11,2460,1760,1958,1987,98008,47.6083,-122.110,3810,30401
18302,6072800246,20140702T000000,3300000.0,5,6.25,8020,21738,2.0,0,0,...,11,8020,0,2001,0,98006,47.5675,-122.189,4160,18969
20460,9808100150,20150402T000000,3345000.0,5,3.75,5350,15360,1.0,0,1,...,11,3040,2310,2008,0,98004,47.6480,-122.218,3740,15940
13967,3126059023,20150303T000000,3395000.0,4,3.50,4730,47870,1.0,1,4,...,10,2940,1790,1954,0,98033,47.6967,-122.216,3250,49346
7989,9362000040,20140623T000000,3400000.0,3,4.50,5230,17826,2.0,1,4,...,10,3740,1490,2005,0,98040,47.5348,-122.243,3670,17826
10446,1118000320,20150508T000000,3400000.0,4,4.00,4260,11765,2.0,0,0,...,11,3280,980,1939,2010,98112,47.6380,-122.288,4260,10408
5880,2525049148,20141007T000000,3418800.0,5,5.00,5450,20412,2.0,0,0,...,11,5450,0,2014,0,98039,47.6209,-122.237,3160,17825
21576,9253900271,20150107T000000,3567000.0,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270
2864,4114601570,20141118T000000,3600000.0,3,3.25,5020,12431,2.0,1,4,...,10,3420,1600,1941,2002,98144,47.5925,-122.287,3680,12620
19148,3625049042,20141011T000000,3635000.0,5,6.00,5490,19897,2.0,0,0,...,12,5490,0,2005,0,98039,47.6165,-122.236,2910,17600
15255,2425049063,20140911T000000,3640900.0,4,3.25,4830,22257,2.0,1,4,...,11,4830,0,1990,0,98039,47.6409,-122.241,3820,25582
18482,4389201095,20150511T000000,3650000.0,5,3.75,5020,8694,2.0,0,1,...,12,3970,1050,2007,0,98004,47.6146,-122.213,4190,11275
6508,4217402115,20150421T000000,3650000.0,6,4.75,5480,19401,1.5,1,4,...,11,3910,1570,1936,0,98105,47.6515,-122.277,3510,15810
16302,7397300170,20140530T000000,3710000.0,4,3.50,5550,28078,2.0,0,2,...,12,3350,2200,2000,0,98039,47.6395,-122.234,2980,19602
7035,853200010,20140701T000000,3800000.0,5,5.50,7050,42840,1.0,0,2,...,13,4320,2730,1978,0,98004,47.6229,-122.220,5070,20570
19017,2303900100,20140911T000000,3800000.0,3,4.25,5510,35000,2.0,0,4,...,13,4910,600,1997,0,98177,47.7296,-122.370,3430,45302
2085,8106100105,20141114T000000,3850000.0,4,4.25,5770,21300,2.0,1,4,...,11,5770,0,1980,0,98040,47.5850,-122.222,4620,22748
4149,6447300265,20141014T000000,4000000.0,4,5.50,7080,16573,2.0,0,0,...,12,5760,1320,2008,0,98039,47.6151,-122.224,3140,15996
12370,6065300370,20150506T000000,4208000.0,5,6.00,7440,21540,2.0,0,0,...,12,5550,1890,2003,0,98006,47.5692,-122.189,4740,19329
8638,3835500195,20140618T000000,4489000.0,4,3.00,6430,27517,2.0,0,0,...,12,6430,0,2001,0,98004,47.6208,-122.219,3720,14592
2626,7738500731,20140815T000000,4500000.0,5,5.50,6640,40014,2.0,1,4,...,12,6350,290,2004,0,98155,47.7493,-122.280,3030,23408
8092,1924059029,20140617T000000,4668000.0,5,6.75,9640,13068,1.0,1,4,...,12,4820,4820,1983,2009,98040,47.5570,-122.210,3270,10454
1164,1247600105,20141020T000000,5110800.0,5,5.25,8010,45517,2.0,1,4,...,12,5990,2020,1999,0,98033,47.6767,-122.211,3430,26788
1315,7558700030,20150413T000000,5300000.0,6,6.00,7390,24829,2.0,1,4,...,12,5000,2390,1991,0,98040,47.5631,-122.210,4320,24619
1448,8907500070,20150413T000000,5350000.0,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
4411,2470100110,20140804T000000,5570000.0,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
9254,9208900037,20140919T000000,6885000.0,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
3914,9808700762,20140611T000000,7062500.0,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
7252,6762700020,20141013T000000,7700000.0,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800

In [11]:
df.sort_values(by=['price','bathrooms'])

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1149,3421079032,20150217T000000,75000.0,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882
15293,40000362,20140506T000000,78000.0,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
465,8658300340,20140523T000000,80000.0,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
16198,3028200080,20150324T000000,81000.0,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
8274,3883800011,20141105T000000,82000.0,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
2141,1623049041,20140508T000000,82500.0,2,1.00,520,22334,1.0,0,0,...,5,520,0,1951,0,98168,47.4799,-122.296,1572,10570
18468,7999600180,20140529T000000,83000.0,2,1.00,900,8580,1.0,0,0,...,5,900,0,1918,0,98168,47.4727,-122.270,2060,6533
3767,1523049188,20150430T000000,84000.0,2,1.00,700,20130,1.0,0,0,...,6,700,0,1949,0,98168,47.4752,-122.271,1490,18630
10253,2422049104,20140915T000000,85000.0,2,1.00,830,9000,1.0,0,0,...,6,830,0,1939,0,98032,47.3813,-122.243,1160,7680
16714,1322049150,20150305T000000,85000.0,2,1.00,910,9753,1.0,0,0,...,5,910,0,1947,0,98032,47.3897,-122.236,1160,7405
13756,1788900230,20140722T000000,86500.0,3,1.00,840,9480,1.0,0,0,...,6,840,0,1960,0,98023,47.3277,-122.341,840,9420
5866,9320900420,20141014T000000,89000.0,3,1.00,900,4750,1.0,0,0,...,6,900,0,1969,0,98023,47.3026,-122.363,900,3404
3108,1721801591,20150219T000000,89950.0,1,1.00,570,4080,1.0,0,0,...,5,570,0,1942,0,98146,47.5098,-122.334,890,5100
7992,2734100835,20150303T000000,90000.0,1,1.00,780,4000,1.0,0,0,...,5,780,0,1905,0,98108,47.5424,-122.321,1150,4000
12551,1049010620,20140513T000000,90000.0,2,1.00,790,2640,1.0,0,0,...,7,790,0,1973,0,98034,47.7351,-122.178,1310,2064
16530,2114700500,20150418T000000,90000.0,1,1.00,560,4120,1.0,0,0,...,4,560,0,1947,0,98106,47.5335,-122.348,980,4120
17580,1423049019,20140523T000000,90000.0,2,1.00,580,7500,1.0,0,0,...,5,580,0,1943,0,98178,47.4852,-122.251,1700,11250
18939,4239400300,20141129T000000,90000.0,3,1.00,980,2490,2.0,0,0,...,6,980,0,1969,0,98092,47.3170,-122.182,980,3154
10770,795000765,20140616T000000,92000.0,2,1.00,760,5500,1.5,0,0,...,5,760,0,1947,0,98168,47.5045,-122.329,1040,5515
3805,7335400215,20150505T000000,95000.0,1,0.75,760,5746,1.0,0,0,...,5,760,0,1915,0,98002,47.3046,-122.215,970,6696
3321,2724200705,20141212T000000,95000.0,2,1.00,800,8550,1.0,0,0,...,7,800,0,1947,0,98198,47.4075,-122.294,1490,8550
10585,6198400218,20140919T000000,95000.0,2,1.00,1070,20450,1.0,0,0,...,6,1070,0,1948,0,98058,47.4338,-122.183,1360,15581
14581,6929602721,20150408T000000,95000.0,2,1.00,960,7000,1.0,0,0,...,4,960,0,1918,0,98198,47.3864,-122.307,1850,8120
5723,1788800630,20141029T000000,96500.0,3,1.00,840,12091,1.0,0,0,...,6,840,0,1959,0,98023,47.3281,-122.343,840,9324
5303,5128000010,20150105T000000,99000.0,2,1.00,960,8236,1.0,0,0,...,6,960,0,1948,0,98058,47.4698,-122.166,1260,8236
16340,6146600170,20140703T000000,100000.0,2,0.75,660,5240,1.0,0,0,...,4,660,0,1912,0,98032,47.3881,-122.234,850,5080
1218,3751600030,20140717T000000,100000.0,2,1.00,770,17334,1.0,0,0,...,7,770,0,1978,0,98001,47.2997,-122.269,1480,17334
3444,7813200115,20140904T000000,100000.0,2,1.00,790,6426,1.0,0,0,...,6,790,0,1944,0,98178,47.4933,-122.245,1380,6946
4563,1900000195,20140630T000000,100000.0,2,1.00,930,7623,1.0,0,0,...,6,930,0,1942,0,98166,47.4670,-122.349,1300,7641
5639,7224000980,20140610T000000,100000.0,4,1.00,1120,2685,1.0,0,0,...,5,860,260,1939,0,98055,47.4904,-122.203,1120,4838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18477,1346300150,20141020T000000,3300000.0,8,4.00,7710,11750,3.5,0,0,...,12,6090,1620,1904,0,98112,47.6263,-122.314,4210,8325
14083,3625059043,20140904T000000,3300000.0,5,4.75,6200,13873,2.0,1,4,...,11,4440,1760,1989,0,98008,47.6050,-122.112,2940,13525
18302,6072800246,20140702T000000,3300000.0,5,6.25,8020,21738,2.0,0,0,...,11,8020,0,2001,0,98006,47.5675,-122.189,4160,18969
20460,9808100150,20150402T000000,3345000.0,5,3.75,5350,15360,1.0,0,1,...,11,3040,2310,2008,0,98004,47.6480,-122.218,3740,15940
13967,3126059023,20150303T000000,3395000.0,4,3.50,4730,47870,1.0,1,4,...,10,2940,1790,1954,0,98033,47.6967,-122.216,3250,49346
10446,1118000320,20150508T000000,3400000.0,4,4.00,4260,11765,2.0,0,0,...,11,3280,980,1939,2010,98112,47.6380,-122.288,4260,10408
7989,9362000040,20140623T000000,3400000.0,3,4.50,5230,17826,2.0,1,4,...,10,3740,1490,2005,0,98040,47.5348,-122.243,3670,17826
5880,2525049148,20141007T000000,3418800.0,5,5.00,5450,20412,2.0,0,0,...,11,5450,0,2014,0,98039,47.6209,-122.237,3160,17825
21576,9253900271,20150107T000000,3567000.0,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270
2864,4114601570,20141118T000000,3600000.0,3,3.25,5020,12431,2.0,1,4,...,10,3420,1600,1941,2002,98144,47.5925,-122.287,3680,12620
19148,3625049042,20141011T000000,3635000.0,5,6.00,5490,19897,2.0,0,0,...,12,5490,0,2005,0,98039,47.6165,-122.236,2910,17600
15255,2425049063,20140911T000000,3640900.0,4,3.25,4830,22257,2.0,1,4,...,11,4830,0,1990,0,98039,47.6409,-122.241,3820,25582
18482,4389201095,20150511T000000,3650000.0,5,3.75,5020,8694,2.0,0,1,...,12,3970,1050,2007,0,98004,47.6146,-122.213,4190,11275
6508,4217402115,20150421T000000,3650000.0,6,4.75,5480,19401,1.5,1,4,...,11,3910,1570,1936,0,98105,47.6515,-122.277,3510,15810
16302,7397300170,20140530T000000,3710000.0,4,3.50,5550,28078,2.0,0,2,...,12,3350,2200,2000,0,98039,47.6395,-122.234,2980,19602
19017,2303900100,20140911T000000,3800000.0,3,4.25,5510,35000,2.0,0,4,...,13,4910,600,1997,0,98177,47.7296,-122.370,3430,45302
7035,853200010,20140701T000000,3800000.0,5,5.50,7050,42840,1.0,0,2,...,13,4320,2730,1978,0,98004,47.6229,-122.220,5070,20570
2085,8106100105,20141114T000000,3850000.0,4,4.25,5770,21300,2.0,1,4,...,11,5770,0,1980,0,98040,47.5850,-122.222,4620,22748
4149,6447300265,20141014T000000,4000000.0,4,5.50,7080,16573,2.0,0,0,...,12,5760,1320,2008,0,98039,47.6151,-122.224,3140,15996
12370,6065300370,20150506T000000,4208000.0,5,6.00,7440,21540,2.0,0,0,...,12,5550,1890,2003,0,98006,47.5692,-122.189,4740,19329
8638,3835500195,20140618T000000,4489000.0,4,3.00,6430,27517,2.0,0,0,...,12,6430,0,2001,0,98004,47.6208,-122.219,3720,14592
2626,7738500731,20140815T000000,4500000.0,5,5.50,6640,40014,2.0,1,4,...,12,6350,290,2004,0,98155,47.7493,-122.280,3030,23408
8092,1924059029,20140617T000000,4668000.0,5,6.75,9640,13068,1.0,1,4,...,12,4820,4820,1983,2009,98040,47.5570,-122.210,3270,10454
1164,1247600105,20141020T000000,5110800.0,5,5.25,8010,45517,2.0,1,4,...,12,5990,2020,1999,0,98033,47.6767,-122.211,3430,26788
1315,7558700030,20150413T000000,5300000.0,6,6.00,7390,24829,2.0,1,4,...,12,5000,2390,1991,0,98040,47.5631,-122.210,4320,24619
1448,8907500070,20150413T000000,5350000.0,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
4411,2470100110,20140804T000000,5570000.0,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
9254,9208900037,20140919T000000,6885000.0,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
3914,9808700762,20140611T000000,7062500.0,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
7252,6762700020,20141013T000000,7700000.0,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800

In [12]:
df.sort_values(by=['price','bathrooms'], ascending=False)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,6762700020,20141013T000000,7700000.0,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800
3914,9808700762,20140611T000000,7062500.0,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
9254,9208900037,20140919T000000,6885000.0,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
4411,2470100110,20140804T000000,5570000.0,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
1448,8907500070,20150413T000000,5350000.0,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
1315,7558700030,20150413T000000,5300000.0,6,6.00,7390,24829,2.0,1,4,...,12,5000,2390,1991,0,98040,47.5631,-122.210,4320,24619
1164,1247600105,20141020T000000,5110800.0,5,5.25,8010,45517,2.0,1,4,...,12,5990,2020,1999,0,98033,47.6767,-122.211,3430,26788
8092,1924059029,20140617T000000,4668000.0,5,6.75,9640,13068,1.0,1,4,...,12,4820,4820,1983,2009,98040,47.5570,-122.210,3270,10454
2626,7738500731,20140815T000000,4500000.0,5,5.50,6640,40014,2.0,1,4,...,12,6350,290,2004,0,98155,47.7493,-122.280,3030,23408
8638,3835500195,20140618T000000,4489000.0,4,3.00,6430,27517,2.0,0,0,...,12,6430,0,2001,0,98004,47.6208,-122.219,3720,14592
12370,6065300370,20150506T000000,4208000.0,5,6.00,7440,21540,2.0,0,0,...,12,5550,1890,2003,0,98006,47.5692,-122.189,4740,19329
4149,6447300265,20141014T000000,4000000.0,4,5.50,7080,16573,2.0,0,0,...,12,5760,1320,2008,0,98039,47.6151,-122.224,3140,15996
2085,8106100105,20141114T000000,3850000.0,4,4.25,5770,21300,2.0,1,4,...,11,5770,0,1980,0,98040,47.5850,-122.222,4620,22748
7035,853200010,20140701T000000,3800000.0,5,5.50,7050,42840,1.0,0,2,...,13,4320,2730,1978,0,98004,47.6229,-122.220,5070,20570
19017,2303900100,20140911T000000,3800000.0,3,4.25,5510,35000,2.0,0,4,...,13,4910,600,1997,0,98177,47.7296,-122.370,3430,45302
16302,7397300170,20140530T000000,3710000.0,4,3.50,5550,28078,2.0,0,2,...,12,3350,2200,2000,0,98039,47.6395,-122.234,2980,19602
6508,4217402115,20150421T000000,3650000.0,6,4.75,5480,19401,1.5,1,4,...,11,3910,1570,1936,0,98105,47.6515,-122.277,3510,15810
18482,4389201095,20150511T000000,3650000.0,5,3.75,5020,8694,2.0,0,1,...,12,3970,1050,2007,0,98004,47.6146,-122.213,4190,11275
15255,2425049063,20140911T000000,3640900.0,4,3.25,4830,22257,2.0,1,4,...,11,4830,0,1990,0,98039,47.6409,-122.241,3820,25582
19148,3625049042,20141011T000000,3635000.0,5,6.00,5490,19897,2.0,0,0,...,12,5490,0,2005,0,98039,47.6165,-122.236,2910,17600
2864,4114601570,20141118T000000,3600000.0,3,3.25,5020,12431,2.0,1,4,...,10,3420,1600,1941,2002,98144,47.5925,-122.287,3680,12620
21576,9253900271,20150107T000000,3567000.0,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270
5880,2525049148,20141007T000000,3418800.0,5,5.00,5450,20412,2.0,0,0,...,11,5450,0,2014,0,98039,47.6209,-122.237,3160,17825
7989,9362000040,20140623T000000,3400000.0,3,4.50,5230,17826,2.0,1,4,...,10,3740,1490,2005,0,98040,47.5348,-122.243,3670,17826
10446,1118000320,20150508T000000,3400000.0,4,4.00,4260,11765,2.0,0,0,...,11,3280,980,1939,2010,98112,47.6380,-122.288,4260,10408
13967,3126059023,20150303T000000,3395000.0,4,3.50,4730,47870,1.0,1,4,...,10,2940,1790,1954,0,98033,47.6967,-122.216,3250,49346
20460,9808100150,20150402T000000,3345000.0,5,3.75,5350,15360,1.0,0,1,...,11,3040,2310,2008,0,98004,47.6480,-122.218,3740,15940
18302,6072800246,20140702T000000,3300000.0,5,6.25,8020,21738,2.0,0,0,...,11,8020,0,2001,0,98006,47.5675,-122.189,4160,18969
14083,3625059043,20140904T000000,3300000.0,5,4.75,6200,13873,2.0,1,4,...,11,4440,1760,1989,0,98008,47.6050,-122.112,2940,13525
18477,1346300150,20141020T000000,3300000.0,8,4.00,7710,11750,3.5,0,0,...,12,6090,1620,1904,0,98112,47.6263,-122.314,4210,8325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3444,7813200115,20140904T000000,100000.0,2,1.00,790,6426,1.0,0,0,...,6,790,0,1944,0,98178,47.4933,-122.245,1380,6946
4563,1900000195,20140630T000000,100000.0,2,1.00,930,7623,1.0,0,0,...,6,930,0,1942,0,98166,47.4670,-122.349,1300,7641
5639,7224000980,20140610T000000,100000.0,4,1.00,1120,2685,1.0,0,0,...,5,860,260,1939,0,98055,47.4904,-122.203,1120,4838
15456,8856000545,20140507T000000,100000.0,2,1.00,910,22000,1.0,0,0,...,6,910,0,1956,0,98001,47.2777,-122.252,1326,9891
16340,6146600170,20140703T000000,100000.0,2,0.75,660,5240,1.0,0,0,...,4,660,0,1912,0,98032,47.3881,-122.234,850,5080
5303,5128000010,20150105T000000,99000.0,2,1.00,960,8236,1.0,0,0,...,6,960,0,1948,0,98058,47.4698,-122.166,1260,8236
5723,1788800630,20141029T000000,96500.0,3,1.00,840,12091,1.0,0,0,...,6,840,0,1959,0,98023,47.3281,-122.343,840,9324
3321,2724200705,20141212T000000,95000.0,2,1.00,800,8550,1.0,0,0,...,7,800,0,1947,0,98198,47.4075,-122.294,1490,8550
10585,6198400218,20140919T000000,95000.0,2,1.00,1070,20450,1.0,0,0,...,6,1070,0,1948,0,98058,47.4338,-122.183,1360,15581
14581,6929602721,20150408T000000,95000.0,2,1.00,960,7000,1.0,0,0,...,4,960,0,1918,0,98198,47.3864,-122.307,1850,8120
3805,7335400215,20150505T000000,95000.0,1,0.75,760,5746,1.0,0,0,...,5,760,0,1915,0,98002,47.3046,-122.215,970,6696
10770,795000765,20140616T000000,92000.0,2,1.00,760,5500,1.5,0,0,...,5,760,0,1947,0,98168,47.5045,-122.329,1040,5515
7992,2734100835,20150303T000000,90000.0,1,1.00,780,4000,1.0,0,0,...,5,780,0,1905,0,98108,47.5424,-122.321,1150,4000
12551,1049010620,20140513T000000,90000.0,2,1.00,790,2640,1.0,0,0,...,7,790,0,1973,0,98034,47.7351,-122.178,1310,2064
16530,2114700500,20150418T000000,90000.0,1,1.00,560,4120,1.0,0,0,...,4,560,0,1947,0,98106,47.5335,-122.348,980,4120
17580,1423049019,20140523T000000,90000.0,2,1.00,580,7500,1.0,0,0,...,5,580,0,1943,0,98178,47.4852,-122.251,1700,11250
18939,4239400300,20141129T000000,90000.0,3,1.00,980,2490,2.0,0,0,...,6,980,0,1969,0,98092,47.3170,-122.182,980,3154
3108,1721801591,20150219T000000,89950.0,1,1.00,570,4080,1.0,0,0,...,5,570,0,1942,0,98146,47.5098,-122.334,890,5100
5866,9320900420,20141014T000000,89000.0,3,1.00,900,4750,1.0,0,0,...,6,900,0,1969,0,98023,47.3026,-122.363,900,3404
13756,1788900230,20140722T000000,86500.0,3,1.00,840,9480,1.0,0,0,...,6,840,0,1960,0,98023,47.3277,-122.341,840,9420
10253,2422049104,20140915T000000,85000.0,2,1.00,830,9000,1.0,0,0,...,6,830,0,1939,0,98032,47.3813,-122.243,1160,7680
16714,1322049150,20150305T000000,85000.0,2,1.00,910,9753,1.0,0,0,...,5,910,0,1947,0,98032,47.3897,-122.236,1160,7405
3767,1523049188,20150430T000000,84000.0,2,1.00,700,20130,1.0,0,0,...,6,700,0,1949,0,98168,47.4752,-122.271,1490,18630
18468,7999600180,20140529T000000,83000.0,2,1.00,900,8580,1.0,0,0,...,5,900,0,1918,0,98168,47.4727,-122.270,2060,6533
2141,1623049041,20140508T000000,82500.0,2,1.00,520,22334,1.0,0,0,...,5,520,0,1951,0,98168,47.4799,-122.296,1572,10570
8274,3883800011,20141105T000000,82000.0,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
16198,3028200080,20150324T000000,81000.0,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
465,8658300340,20140523T000000,80000.0,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
15293,40000362,20140506T000000,78000.0,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
1149,3421079032,20150217T000000,75000.0,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882

In [13]:
df[(df['bathrooms']==2)&(df['price']<150000)].sort_values(by='price', ascending=False)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15144,1823049182,20140915T000000,147400.0,3,2.0,1080,9225,1.0,0,0,...,7,1080,0,1955,0,98146,47.4842,-122.346,1410,9840
15810,7129304540,20141220T000000,133000.0,5,2.0,1430,5600,1.5,0,0,...,6,1430,0,1947,0,98118,47.5192,-122.266,1860,5980
12208,4031000520,20140708T000000,115000.0,1,2.0,1150,9812,1.0,0,0,...,7,1150,0,1962,0,98001,47.2951,-122.284,1200,9812

In [14]:
df[(df['bathrooms']==2)&(df['price']<200000)].sort_values(by='price', ascending=False)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
10916,7227800055,20140909T000000,199500.0,4,2.0,1750,8116,1.0,0,0,...,5,1750,0,1943,0,98056,47.5097,-122.181,1440,7865
14719,7227800065,20141016T000000,199000.0,4,2.0,1440,9477,1.0,0,0,...,5,1440,0,1943,0,98056,47.5093,-122.182,1440,9546
2769,3352401981,20140521T000000,199000.0,4,2.0,2030,8120,2.0,0,0,...,7,2030,0,1950,0,98178,47.4994,-122.261,1520,9440
12241,7682200320,20150409T000000,197400.0,3,2.0,1610,7575,1.0,0,0,...,7,1110,500,1965,0,98003,47.3340,-122.300,1920,8400
6958,3279000460,20140926T000000,196500.0,3,2.0,1310,7000,1.0,0,0,...,7,1310,0,1979,0,98023,47.3030,-122.383,1390,7500
1691,3356406510,20140530T000000,196440.0,3,2.0,1560,7352,1.0,0,0,...,6,1560,0,1992,0,98001,47.2804,-122.251,1120,7950
2877,2781270090,20150225T000000,195000.0,2,2.0,1180,2553,2.0,0,0,...,6,1180,0,2005,0,98038,47.3501,-122.020,1310,2687
11481,6083000071,20141110T000000,195000.0,3,2.0,1230,8235,1.5,0,0,...,6,1230,0,1959,0,98168,47.4853,-122.304,1080,10281
14601,2501600150,20150310T000000,194000.0,4,2.0,1760,7700,1.0,0,0,...,7,1760,0,1962,0,98003,47.3299,-122.318,1870,7316
16667,7153400010,20140812T000000,190500.0,3,2.0,1390,10155,1.0,0,0,...,7,1130,260,1980,0,98003,47.2575,-122.305,1790,10155
1928,3972900160,20150403T000000,190000.0,4,2.0,1580,6250,1.0,0,0,...,7,860,720,1977,0,98155,47.7659,-122.310,1580,6250
19155,7227800040,20140604T000000,190000.0,5,2.0,1750,10284,1.0,0,0,...,5,1750,0,1943,0,98056,47.5094,-122.182,1560,9010
3244,1545805490,20141006T000000,190000.0,3,2.0,1320,7625,1.0,0,0,...,7,1320,0,1987,0,98038,47.3635,-122.045,1420,7500
1737,5402100045,20150311T000000,189950.0,4,2.0,1910,4225,1.0,0,0,...,6,910,1000,1919,0,98001,47.3084,-122.234,1060,4800
11419,7116500125,20140528T000000,189000.0,2,2.0,1700,3171,1.0,0,0,...,5,850,850,1927,0,98002,47.3025,-122.224,1380,5906
3369,9407101380,20141230T000000,189000.0,3,2.0,1460,11481,1.0,0,0,...,7,1170,290,1995,0,98045,47.4493,-121.777,1540,9680
18478,9268710220,20140528T000000,186950.0,2,2.0,1390,1302,2.0,0,0,...,7,1390,0,1986,0,98003,47.3089,-122.330,1390,1302
8164,3141600210,20140619T000000,186000.0,3,2.0,1340,4320,1.0,0,0,...,5,920,420,1912,1993,98002,47.2990,-122.228,980,6480
16087,5198600010,20140819T000000,180000.0,3,2.0,1670,7056,1.0,0,0,...,7,1670,0,1958,0,98002,47.3139,-122.212,1330,8415
2002,7335400400,20150410T000000,176250.0,4,2.0,1440,6702,1.0,0,0,...,7,1440,0,1966,0,98002,47.3056,-122.217,1030,6702
17021,6404600006,20140820T000000,173250.0,3,2.0,1210,9097,1.0,0,0,...,7,1210,0,1954,0,98168,47.4849,-122.303,1360,10125
12942,7148200040,20150210T000000,173000.0,4,2.0,1200,8460,1.0,0,0,...,7,1200,0,1957,0,98188,47.4413,-122.277,1350,8623
2352,7229700105,20150424T000000,172500.0,2,2.0,1510,20685,1.0,0,0,...,6,1250,260,1958,0,98059,47.4810,-122.116,1490,29527
118,3454800060,20150108T000000,171800.0,4,2.0,1570,9600,1.0,0,0,...,6,1570,0,1950,0,98168,47.4965,-122.303,1880,9000
19563,42000245,20140613T000000,171000.0,4,2.0,1520,19672,1.0,0,0,...,6,1020,500,1920,0,98188,47.4683,-122.281,1810,7840
9234,302000375,20140814T000000,169100.0,3,2.0,1050,18304,1.0,0,0,...,7,1050,0,1953,0,98001,47.3206,-122.269,1690,15675
4312,4331000265,20140926T000000,167000.0,3,2.0,1520,7456,1.0,0,0,...,7,1520,0,1949,0,98166,47.4745,-122.343,1740,8464
19131,2724201202,20150304T000000,163000.0,2,2.0,1250,7543,1.0,0,0,...,7,1250,0,1962,0,98198,47.4051,-122.296,1250,7506
2832,7227801955,20140919T000000,162000.0,4,2.0,1440,7641,1.0,0,0,...,5,1440,0,1943,0,98056,47.5080,-122.183,1440,7750
13183,1523049207,20140805T000000,161000.0,4,2.0,1700,8043,1.0,0,0,...,7,850,850,1954,0,98168,47.4758,-122.288,1540,13260
3361,7135300026,20141224T000000,160000.0,2,2.0,1040,4750,1.0,0,0,...,6,850,190,1950,0,98118,47.5293,-122.272,1350,5000
5407,7129300595,20150506T000000,158000.0,3,2.0,1090,6090,1.0,0,0,...,7,940,150,1940,0,98118,47.5118,-122.259,1840,6090
13228,2976800749,20141031T000000,150000.0,4,2.0,1460,7254,1.0,0,0,...,6,1460,0,1959,0,98178,47.5056,-122.254,1460,7236
15144,1823049182,20140915T000000,147400.0,3,2.0,1080,9225,1.0,0,0,...,7,1080,0,1955,0,98146,47.4842,-122.346,1410,9840
15810,7129304540,20141220T000000,133000.0,5,2.0,1430,5600,1.5,0,0,...,6,1430,0,1947,0,98118,47.5192,-122.266,1860,5980
12208,4031000520,20140708T000000,115000.0,1,2.0,1150,9812,1.0,0,0,...,7,1150,0,1962,0,98001,47.2951,-122.284,1200,9812

In [15]:
df[11:20]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
11,9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
12,114101516,20140528T000000,310000.0,3,1.00,1430,19901,1.5,0,0,...,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
13,6054650070,20141007T000000,400000.0,3,1.75,1370,9680,1.0,0,0,...,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,1175000570,20150312T000000,530000.0,5,2.00,1810,4850,1.5,0,0,...,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
15,9297300055,20150124T000000,650000.0,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
16,1875500060,20140731T000000,395000.0,3,2.00,1890,14040,2.0,0,0,...,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
17,6865200140,20140529T000000,485000.0,4,1.00,1600,4300,1.5,0,0,...,7,1600,0,1916,0,98103,47.6648,-122.343,1610,4300
18,16000397,20141205T000000,189000.0,2,1.00,1200,9850,1.0,0,0,...,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
19,7983200060,20150424T000000,230000.0,3,1.00,1250,9774,1.0,0,0,...,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850

In [16]:
df.iloc[0:3,0:5]

           id             date     price  bedrooms  bathrooms
0  7129300520  20141013T000000  221900.0         3       1.00
1  6414100192  20141209T000000  538000.0         3       2.25
2  5631500400  20150225T000000  180000.0         2       1.00

In [17]:
df['bathrooms']

0        1.00
1        2.25
2        1.00
3        3.00
4        2.00
5        4.50
6        2.25
7        1.50
8        1.00
9        2.50
10       2.50
11       1.00
12       1.00
13       1.75
14       2.00
15       3.00
16       2.00
17       1.00
18       1.00
19       1.00
20       1.75
21       2.75
22       2.50
23       1.50
24       2.25
25       2.00
26       1.75
27       1.00
28       1.75
29       2.50
         ...
21583    1.00
21584    2.50
21585    2.50
21586    2.50
21587    2.50
21588    1.50
21589    2.50
21590    3.50
21591    2.75
21592    2.25
21593    3.75
21594    2.75
21595    2.25
21596    2.75
21597    3.25
21598    2.50
21599    3.00
21600    3.75
21601    2.50
21602    1.75
21603    2.50
21604    2.00
21605    2.50
21606    3.50
21607    2.50
21608    2.50
21609    2.50
21610    0.75
21611    2.50
21612    0.75
Name: bathrooms, Length: 21613, dtype: float64

In [20]:
df [['bedrooms', 'sqft_living']]

       bedrooms  sqft_living
0             3         1180
1             3         2570
2             2          770
3             4         1960
4             3         1680
5             4         5420
6             3         1715
7             3         1060
8             3         1780
9             3         1890
10            3         3560
11            2         1160
12            3         1430
13            3         1370
14            5         1810
15            4         2950
16            3         1890
17            4         1600
18            2         1200
19            3         1250
20            4         1620
21            3         3050
22            5         2270
23            2         1070
24            3         2450
25            3         1710
26            3         2450
27            3         1400
28            3         1520
29            4         2570
...         ...          ...
21583         2          710
21584         3         1260
21585         3         1870
21586         2         1430
21587         3         1520
21588         2         1210
21589         3         2540
21590         4         4910
21591         4         2770
21592         3         1190
21593         5         4170
21594         4         2500
21595         2         1530
21596         5         3600
21597         4         3410
21598         4         3118
21599         4         3990
21600         5         4470
21601         3         1425
21602         3         1500
21603         3         2270
21604         3         1490
21605         4         2520
21606         4         3510
21607         3         1310
21608         3         1530
21609         4         2310
21610         2         1020
21611         3         1600
21612         2         1020

[21613 rows x 2 columns]

In [25]:
df.groupby(by='bedrooms')['price'].mean().round()

bedrooms
0      409504.0
1      317643.0
2      401373.0
3      466232.0
4      635420.0
5      786600.0
6      825521.0
7      951185.0
8     1105077.0
9      894000.0
10     819333.0
11     520000.0
33     640000.0
Name: price, dtype: float64

In [26]:
df.groupby(by=['bedrooms', 'bathrooms'])['price'].mean().round()

bedrooms  bathrooms
0         0.00          520371.0
          0.75          265000.0
          1.00          228000.0
          1.50          288000.0
          2.50          299983.0
1         0.00          279667.0
          0.50          255000.0
          0.75          251054.0
          1.00          316630.0
          1.25          881750.0
          1.50          325746.0
          1.75          366050.0
          2.00          297167.0
          2.25          436225.0
          2.50          489500.0
2         0.50          191000.0
          0.75          327514.0
          1.00          348073.0
          1.25          468983.0
          1.50          410121.0
          1.75          471249.0
          2.00          448356.0
          2.25          517655.0
          2.50          540897.0
          2.75          550942.0
          3.00          644588.0
          3.25          866650.0
          3.50          535000.0
3         0.75          311513.0
          1.00          336185.0
                         ...
7         3.00         1218333.0
          3.25          419000.0
          3.50         1002000.0
          3.75          831580.0
          4.00          689991.0
          4.25         1637000.0
          4.50         1535000.0
          4.75         1592450.0
          5.50         1240000.0
          5.75          540000.0
          6.75          800000.0
          8.00         2280000.0
8         2.50          700000.0
          2.75          890000.0
          3.00          474000.0
          3.25          430000.0
          3.50         1970000.0
          3.75          808000.0
          4.00         2100000.0
          5.00          490000.0
          6.00         2150000.0
9         3.00          817000.0
          4.00         1400000.0
          4.50          940000.0
          7.50          450000.0
10        2.00          650000.0
          3.00          660000.0
          5.25         1148000.0
11        3.00          520000.0
33        1.75          640000.0
Name: price, Length: 144, dtype: float64

In [28]:
import numpy as np

In [33]:
df.groupby(by='bedrooms')['price'].agg([np.sum, np.mean, np.median, np.var, np.std, np.min, np.max])

,sum,mean,median,var,std,amin,amax
bedrooms,,,,,,,
0,5.323550e+06,4.095038e+05,288000.0,1.286532e+11,358682.627507,139950.0,1295650.0
1,6.321093e+07,3.176429e+05,299000.0,2.216077e+10,148864.955017,75000.0,1247000.0
2,1.107789e+09,4.013727e+05,374000.0,3.922453e+10,198051.827269,78000.0,3278000.0
3,4.580264e+09,4.662321e+05,413000.0,6.889038e+10,262469.771863,82000.0,3800000.0
4,4.372957e+09,6.354195e+05,549997.5,1.510056e+11,388594.441911,100000.0,4489000.0
5,1.259346e+09,7.865998e+05,620000.0,3.554592e+11,596204.003693,133000.0,7062500.0
6,2.245416e+08,8.255206e+05,650000.0,6.387827e+11,799238.819958,175000.0,7700000.0
7,3.614502e+07,9.511847e+05,728580.0,5.475313e+11,739953.558961,280000.0,3200000.0
8,1.436600e+07,1.105077e+06,700000.0,8.054986e+11,897495.725295,340000.0,3300000.0
9,5.363999e+06,8.939998e+05,817000.0,1.455681e+11,381533.900984,450000.0,1400000.0
10,2.458000e+06,8.193333e+05,660000.0,8.104133e+10,284677.595419,650000.0,1148000.0
11,5.200000e+05,5.200000e+05,520000.0,NaN,NaN,520000.0,520000.0
33,6.400000e+05,6.400000e+05,640000.0,NaN,NaN,640000.0,640000.0

In [30]:
df.pivot_table(index='zipcode', columns='bedrooms', values='price', aggfunc=np.mean).round()

bedrooms,0,1,2,3,4,5,6,7,8,9,10,11,33
zipcode,,,,,,,,,,,,,
98001,139950.0,169333.0,217795.0,256070.0,325340.0,318516.0,230000.0,NaN,NaN,NaN,NaN,NaN,NaN
98002,NaN,116500.0,187162.0,224579.0,261098.0,270600.0,317750.0,NaN,NaN,NaN,NaN,NaN,NaN
98003,NaN,360000.0,215894.0,265377.0,344254.0,428175.0,350500.0,NaN,NaN,NaN,NaN,NaN,NaN
98004,NaN,NaN,810607.0,1014349.0,1422505.0,1865356.0,1223000.0,2300000.0,1900000.0,NaN,1148000.0,NaN,NaN
98005,NaN,NaN,780000.0,692643.0,865821.0,880197.0,967167.0,NaN,NaN,NaN,NaN,NaN,NaN
98006,NaN,NaN,864681.0,679875.0,923401.0,1032163.0,1108588.0,1240000.0,NaN,NaN,650000.0,NaN,NaN
98007,NaN,NaN,454820.0,546058.0,686244.0,651174.0,660667.0,829333.0,NaN,NaN,NaN,NaN,NaN
98008,NaN,NaN,896367.0,580785.0,619291.0,849020.0,651917.0,770000.0,NaN,NaN,NaN,NaN,NaN
98010,NaN,440000.0,308650.0,366626.0,545879.0,345466.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98011,NaN,310000.0,368222.0,473202.0,494498.0,595364.0,520417.0,NaN,NaN,NaN,NaN,NaN,NaN
98014,NaN,305236.0,317262.0,421774.0,641518.0,855500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98019,NaN,307617.0,351094.0,377024.0,498539.0,527579.0,640000.0,NaN,NaN,NaN,NaN,NaN,NaN
98022,NaN,191480.0,275262.0,305547.0,365283.0,367200.0,406000.0,NaN,NaN,NaN,NaN,NaN,NaN
98023,NaN,NaN,259462.0,262645.0,317435.0,359310.0,345450.0,NaN,NaN,NaN,NaN,NaN,NaN
98024,142000.0,NaN,389767.0,459986.0,834024.0,812421.0,1600000.0,NaN,NaN,NaN,NaN,NaN,NaN
98027,NaN,550000.0,363873.0,531322.0,728376.0,785354.0,592750.0,720000.0,NaN,NaN,NaN,NaN,NaN
98028,NaN,NaN,305989.0,434972.0,508619.0,530291.0,663333.0,NaN,NaN,NaN,NaN,NaN,NaN
98029,NaN,NaN,411370.0,527765.0,716677.0,899682.0,1150000.0,NaN,NaN,NaN,NaN,NaN,NaN
98030,NaN,NaN,224556.0,271370.0,326588.0,345112.0,358750.0,NaN,NaN,NaN,NaN,NaN,NaN
98031,355000.0,NaN,248605.0,278641.0,322298.0,326868.0,546667.0,NaN,NaN,NaN,NaN,NaN,NaN
98032,NaN,NaN,177804.0,236813.0,284770.0,297044.0,320000.0,NaN,NaN,NaN,NaN,NaN,NaN
98033,NaN,448450.0,548669.0,632017.0,926148.0,1228299.0,1030500.0,597157.0,NaN,NaN,NaN,NaN,NaN
98034,NaN,NaN,393748.0,491506.0,583368.0,559927.0,482471.0,NaN,575000.0,NaN,NaN,NaN,NaN
98038,240000.0,246500.0,263319.0,334962.0,407430.0,477709.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98039,NaN,NaN,1550000.0,1308136.0,2144451.0,2649505.0,6885000.0,2450000.0,NaN,NaN,NaN,NaN,NaN
98040,NaN,NaN,714650.0,966017.0,1180307.0,1413918.0,1841125.0,1417450.0,NaN,NaN,NaN,NaN,NaN
98042,339950.0,129000.0,256182.0,285755.0,351263.0,390111.0,383167.0,NaN,NaN,NaN,NaN,NaN,NaN
98045,NaN,298000.0,326697.0,397216.0,555026.0,635777.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98052,NaN,NaN,445725.0,581871.0,705183.0,757487.0,612889.0,NaN,NaN,NaN,NaN,NaN,NaN
98053,1295650.0,442000.0,553353.0,569388.0,831156.0,854238.0,635000.0,2280000.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98092,NaN,250000.0,312500.0,303295.0,370324.0,370085.0,400000.0,280000.0,NaN,NaN,NaN,NaN,NaN
98102,1095000.0,NaN,534685.0,816324.0,1072696.0,1305740.0,3391400.0,750000.0,NaN,700000.0,NaN,NaN,NaN
98103,NaN,418883.0,483181.0,559542.0,750799.0,797046.0,899890.0,550000.0,NaN,599999.0,NaN,NaN,640000.0
98105,NaN,525000.0,544412.0,766505.0,1082927.0,961000.0,1394369.0,730000.0,754000.0,1204667.0,660000.0,NaN,NaN
98106,NaN,211890.0,273010.0,318725.0,356067.0,421513.0,319000.0,419000.0,NaN,NaN,NaN,520000.0,NaN
98107,NaN,343000.0,492573.0,570245.0,652645.0,884141.0,796688.0,NaN,900000.0,NaN,NaN,NaN,NaN
98108,NaN,198000.0,312952.0,346462.0,401684.0,422212.0,398700.0,NaN,NaN,NaN,NaN,NaN,NaN
98109,NaN,447500.0,673395.0,788253.0,1157718.0,979167.0,563000.0,3200000.0,NaN,NaN,NaN,NaN,NaN
98112,NaN,424250.0,620824.0,957775.0,1366110.0,1255870.0,1485714.0,2885000.0,1983333.0,NaN,NaN,NaN,NaN
98115,NaN,400081.0,474776.0,583189.0,738742.0,844956.0,655667.0,NaN,NaN,NaN,NaN,NaN,NaN
98116,NaN,373441.0,500075.0,599300.0,768048.0,676845.0,922500.0,NaN,NaN,NaN,NaN,NaN,NaN
98117,NaN,350996.0,470679.0,563519.0,719709.0,701132.0,918261.0,830720.0,NaN,NaN,NaN,NaN,NaN
98118,228000.0,336000.0,340884.0,396941.0,512974.0,533285.0,577999.0,370500.0,NaN,NaN,NaN,NaN,NaN
98119,NaN,NaN,615126.0,739316.0,1012736.0,1444909.0,1469000.0,NaN,NaN,NaN,NaN,NaN,NaN
98122,NaN,366286.0,486669.0,631206.0,742556.0,879383.0,697900.0,599000.0,490000.0,NaN,NaN,NaN,NaN
98125,288000.0,365333.0,381345.0,446360.0,550489.0,653294.0,521994.0,520000.0,NaN,NaN,NaN,NaN,NaN
98126,NaN,275269.0,342310.0,448490.0,530348.0,568000.0,647833.0,NaN,NaN,NaN,NaN,NaN,NaN
98133,380000.0,292075.0,323889.0,380424.0,444713.0,464294.0,453167.0,512500.0,340000.0,NaN,NaN,NaN,NaN
98136,NaN,350675.0,404552.0,575101.0,692964.0,846944.0,767500.0,NaN,NaN,NaN,NaN,NaN,NaN
98144,NaN,330385.0,407828.0,556280.0,738152.0,857740.0,931289.0,853800.0,NaN,450000.0,NaN,NaN,NaN
98146,NaN,237089.0,315517.0,338364.0,437332.0,379632.0,521383.0,NaN,NaN,NaN,NaN,NaN,NaN
98148,NaN,NaN,234400.0,269585.0,330624.0,569950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98155,NaN,305000.0,316302.0,383120.0,476118.0,677932.0,506800.0,480000.0,NaN,NaN,NaN,NaN,NaN
98166,NaN,225667.0,374613.0,472320.0,471773.0,485528.0,623288.0,800000.0,NaN,NaN,NaN,NaN,NaN
98168,NaN,214658.0,200580.0,248458.0,259730.0,312255.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98177,NaN,319000.0,486913.0,650899.0,698135.0,953831.0,1084660.0,NaN,NaN,NaN,NaN,NaN,NaN
98178,NaN,231000.0,258323.0,274831.0,366566.0,383477.0,455333.0,NaN,NaN,NaN,NaN,NaN,NaN
98188,NaN,NaN,231617.0,260234.0,329309.0,348768.0,383700.0,NaN,NaN,NaN,NaN,NaN,NaN
98198,NaN,279417.0,222099.0,298762.0,353677.0,345718.0,279000.0,NaN,NaN,NaN,NaN,NaN,NaN
98199,NaN,438667.0,544543.0,741163.0,949757.0,1211962.0,1669500.0,824000.0,NaN,NaN,NaN,NaN,NaN

In [36]:
df['date']=pd.to_datetime(df['date'])
df.head(3)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062

In [38]:
 df['sqm_living'] = df['sqft_living']/10.764
 df.head(3)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sqm_living
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,109.624675
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,238.758826
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,71.534745

In [39]:
df.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sqm_living
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,...,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,...,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652,193.227400
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,...,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631,85.325241
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,26.941657
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,...,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000,132.571535
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,...,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000,177.443330
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,...,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,236.900780
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,...,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,1257.896693

In [40]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,21613.0,4.580302e+09,2.876566e+09,1.000102e+06,2.123049e+09,3.904930e+09,7.308900e+09,9.900000e+09
price,21613.0,5.400881e+05,3.671272e+05,7.500000e+04,3.219500e+05,4.500000e+05,6.450000e+05,7.700000e+06
bedrooms,21613.0,3.370842e+00,9.300618e-01,0.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,3.300000e+01
bathrooms,21613.0,2.114757e+00,7.701632e-01,0.000000e+00,1.750000e+00,2.250000e+00,2.500000e+00,8.000000e+00
sqft_living,21613.0,2.079900e+03,9.184409e+02,2.900000e+02,1.427000e+03,1.910000e+03,2.550000e+03,1.354000e+04
sqft_lot,21613.0,1.510697e+04,4.142051e+04,5.200000e+02,5.040000e+03,7.618000e+03,1.068800e+04,1.651359e+06
floors,21613.0,1.494309e+00,5.399889e-01,1.000000e+00,1.000000e+00,1.500000e+00,2.000000e+00,3.500000e+00
waterfront,21613.0,7.541757e-03,8.651720e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
view,21613.0,2.343034e-01,7.663176e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
condition,21613.0,3.409430e+00,6.507430e-01,1.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00
grade,21613.0,7.656873e+00,1.175459e+00,1.000000e+00,7.000000e+00,7.000000e+00,8.000000e+00,1.300000e+01
sqft_above,21613.0,1.788391e+03,8.280910e+02,2.900000e+02,1.190000e+03,1.560000e+03,2.210000e+03,9.410000e+03
sqft_basement,21613.0,2.915090e+02,4.425750e+02,0.000000e+00,0.000000e+00,0.000000e+00,5.600000e+02,4.820000e+03
yr_built,21613.0,1.971005e+03,2.937341e+01,1.900000e+03,1.951000e+03,1.975000e+03,1.997000e+03,2.015000e+03
yr_renovated,21613.0,8.440226e+01,4.016792e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.015000e+03
zipcode,21613.0,9.807794e+04,5.350503e+01,9.800100e+04,9.803300e+04,9.806500e+04,9.811800e+04,9.819900e+04
lat,21613.0,4.756005e+01,1.385637e-01,4.715590e+01,4.747100e+01,4.757180e+01,4.767800e+01,4.777760e+01
long,21613.0,-1.222139e+02,1.408283e-01,-1.225190e+02,-1.223280e+02,-1.222300e+02,-1.221250e+02,-1.213150e+02
sqft_living15,21613.0,1.986552e+03,6.853913e+02,3.990000e+02,1.490000e+03,1.840000e+03,2.360000e+03,6.210000e+03
sqft_lot15,21613.0,1.276846e+04,2.730418e+04,6.510000e+02,5.100000e+03,7.620000e+03,1.008300e+04,8.712000e+05
sqm_living,21613.0,1.932274e+02,8.532524e+01,2.694166e+01,1.325715e+02,1.774433e+02,2.369008e+02,1.257897e+03

In [41]:
np.mean(df['price'])

540088.1417665294